# Generated by Django 6.0.1 on 2026-01-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "worker", "verbose_name_plural": "workers"},
        ),
    ]
